services:
  - type: web
    name: arena-ai-chess
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9" 